@extends('layouts.app')
@section('content')
<header-comp 
    menova_img="{{asset('/storage/images/menova.png')}}" 
    background="{{asset('/storage/images/header-bg.jpg')}}"
    header_heading="@lang('home.header_heading')"
    header_sub="@lang('home.header_sub_heading')"
    header_sub="@lang('home.header_sub_heading')"
    >
</header-comp>
@endsection
